### ISSUE TITLE
Need clarification in the Developer Intermediate, Code Analysis tutorial

### ISSUE THREAD

**Issue by annumberhocker** [ibm-gsi-ecosystem/ibm-gsi-cloudnative-journey#109]
**Describe the bug**
Documentation at [Code Analysis](https://ibm-gsi-ecosystem.github.io/ibm-gsi-cloudnative-journey/developer-intermediate/code-analysis#code-analysis-in-the-pipeline) needs to be updated from 

> Deploy the Code Pattern named Spring Boot Microservice.
> 
> Follow the directions in Deploying an App
> Deploy the `Spring Boot Microservice` template
> Name the new repo something like `sonar-java`
> Be sure to run the CI pipeline for your project, and confirm that it runs the Sonar scan stage

To add additional steps:

> Follow the directions in Deploying an App
> Deploy the `Spring Boot Microservice` template
> Name the new repo something like `sonar-java`
> _Edit the `settings.gradle` file and change the application name to something like `sonar-java-xx`_
> _Add, Commit and Push the changes into new repo_
> _Be sure to run the CI pipeline for your project, and confirm that it runs the Sonar scan in the `test` stage_

**Comment by RamyaRaghuveera** [comment]
Hi,
Thanks for raising the issue. 

- The code analysis documentation asks to refer to ["Deploying an App"](https://ibm-gsi-ecosystem.github.io/ibm-gsi-cloudnative-journey/developer-intermediate/deploy-app/) for deploying the app. The Deploying an app documentation clearly mentions changing the name from template name to your chosen name and also mentions to change it in package.json for projects which have that file in ["Clone your code"](https://ibm-gsi-ecosystem.github.io/ibm-gsi-cloudnative-journey/developer-intermediate/deploy-app/#5.-clone-your-code). 

- For Spring Boot Microservice template, we need to change "rootProject.name" in settings.gradle for it to reflect in Sonarqube UI. The pipeline name gets updated to git repository name but SonarQube UI picks up the name from settings.gradle file only. Thanks a lot for pointing this out. 

- We need to make this change in ["Deploying an App"](https://ibm-gsi-ecosystem.github.io/ibm-gsi-cloudnative-journey/developer-intermediate/deploy-app/) and [Spring Boot Microservice template](https://github.com/IBM/template-java-spring)  README file as SonarQube is part of each and every pipeline we run. We will make sure the change is in place. 

-  We will change "Be sure to run the CI pipeline for your project, and confirm that it runs the Sonar scan stage" to "Be sure to run the CI pipeline for your project, and confirm that it runs the Sonar scan in the test stage". The instruction refers Openshift 3.11 pipeline.

Thanks & Regards,
Ramya Raghuveera
