### ISSUE TITLE
Link to instructions for Cloudant setup

### ISSUE THREAD

**Issue by jeancarl** [ibm-gsi-ecosystem/ibm-gsi-cloudnative-journey#112]
**Describe the bug**

Deploying the Inventory Services app from the pre-built solution (https://ibm-gsi-ecosystem.github.io/ibm-gsi-cloudnative-journey/developer-intermediate/inventory-app) fails because it relies on Cloudant credentials. This is actually mentioned in the Advanced section (https://ibm-gsi-ecosystem.github.io/ibm-gsi-cloudnative-journey/developer-advanced/inventory-cloudant).

**Expected behavior**

The instructions to deploy the pre-built solution for the Inventory app, https://ibm-gsi-ecosystem.github.io/ibm-gsi-cloudnative-journey/developer-intermediate/inventory-app/, should link to how to setup Cloudant credentials.

**Comment by RamyaRaghuveera** [comment]
Hi Jean,

We have seperated the cloudant code from Deploying the Inventory Services App from the pre-built solution(https://ibm-gsi-ecosystem.github.io/ibm-gsi-cloudnative-journey/developer-intermediate/inventory-app/#deploy-the-inventory-app-solution). The code (https://github.com/ibm-gsi-ecosystem/inventory-management-svc-solution/tree/master/src/main/java/com/ibm/inventory_management) can be run without cloudant credentials now.

Thanks & Regards,
Ramya

**Comment by jeancarl** [comment]
Pre-built solution deploys successfully.
