### ISSUE TITLE
The Migrate to OpenShift content is broken due to missing repo

### ISSUE THREAD

**Issue by binnes** [ibm-gsi-ecosystem/ibm-gsi-cloudnative-journey#181]
The App Modernization content in the Intermediate section is broken as the final Migrate to OpenShift - https://ibm-gsi-ecosystem.github.io/ibm-gsi-cloudnative-journey/developer-intermediate/appmod-exercise1-part3/ content cannot be completed due to a missing git repo : https://github.com/ibm-gsi-ecosystem/appmod-plants-app.git, where a number of assets need to copied from to allow the deploy of the migrated app.

**Comment by mjperrins** [comment]
@abalasu1 can we fix this ? or at least update with latest material from Carlos workshop model ?

**Comment by balassree** [comment]
@abalasu1 @mjperrins  The repo was turned to private, hence the issue. Now the Repository "https://github.com/ibm-gsi-ecosystem/appmod-plants-app.git"  is made as Public and should be accessible.
